[workspace]
authors = ["Martin Durant <martin.durant@alumni.utoronto.ca>"]
channels = ["conda-forge"]
name = "projspec"
platforms = ["osx-arm64"]
preview = ["pixi-build"]

[tasks]
go = "projspec"  # run's the project's standard executable

[dependencies]
fsspec = "2025.5.*"
pyyaml = "*"
toml = "*"

[pypi-dependencies]
projspec = { path = ".", editable = true }

[package]
name = "projspec"
version = "0.1.0"

[package.host-dependencies]
hatchling = "*"
hatch-vcs = "*"

[package.build]
backend = { name = "pixi-build-python", version = "*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
